### ISSUE TITLE
Ao ativar atualização local via NTP acontece um NPE

### ISSUE THREAD

**Issue by spolti** [hrstatus/hrstatus#98]
02:56:05,006 FINE  [br.com.hrstatus.scheduler.MainScheduler] (Scheduler-6) Iniciando checagem NTP
02:56:05,008 ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler] (Scheduler-6) Unexpected error occurred in scheduled task.: java.lang.NullPointerException
	at br.com.hrstatus.utils.UserInfo.getLoggedUsername(UserInfo.java:36) [classes:]
	at br.com.hrstatus.dao.impl.ConfigurationDAO.getNtpServerAddress(ConfigurationDAO.java:183) [classes:]

**Comment by spolti** [comment]
Fixed: 
17:23:05,138 FINE  [br.com.hrstatus.scheduler.MainScheduler] (Scheduler-1) Iniciando checagem NTP
17:23:05,140 FINE  [br.com.hrstatus.dao.impl.ConfigurationDAO] (Scheduler-1) [ System ] getNtpServerAddress()
17:23:05,148 FINE  [br.com.hrstatus.scheduler.MainScheduler] (Scheduler-1) Servidor NTP configurado: a.st1.ntp.br
17:23:11,545 FINE  [br.com.hrstatus.scheduler.MainScheduler] (Scheduler-1) Result of ntp update [ sudo /usr/sbin/ntpdate
 -u a.st1.ntp.br]:  4 Jan 17:23:11 ntpdate[9010]: adjust time server 200.160.7.186 offset 0.000529 sec
